spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hostlog?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    resources: static-locations=classpath:/static/

mybatis:
  mapper-locations: classpath:mapper/Mapper.xml
server:
  port: 8080


